export const categorias = [
  { categoria: "Ingreso" },
  { categoria: "Gasto" },
  { categoria: "Total" },
  { categoria: "Categoría" },
  { categoria: "Dinero" },
  { categoria: "Presupuesto" },
  { categoria: "Balance" },
  { categoria: "Fecha" },
  { categoria: "Guardar" },
  { categoria: "Editar" },
  { categoria: "Eliminar" },
  { categoria: "Gráfico" },
  { categoria: "Informe" },
  { categoria: "Mensual" },
  { categoria: "Diario" },
  { categoria: "Anual" },
  { categoria: "Transacción" },
  { categoria: "Recurrente" },
  { categoria: "Saldo" },
  { categoria: "Descripción" },
  { categoria: "Meta" },
  { categoria: "Inversión" },
  { categoria: "Débito" },
  { categoria: "Crédito" },
  { categoria: "Ahorro" },
  { categoria: "Cuenta" },
  { categoria: "Configuración" },
  { categoria: "Personalizar" },
  { categoria: "Notificación" },
  { categoria: "Resumen" },
  { categoria: "Historial" },
  { categoria: "Reporte" },
  { categoria: "Objetivo" },
  { categoria: "Pagado" },
  { categoria: "Por pagar" },
  { categoria: "Pendiente" },
  { categoria: "Ajustes" },
  { categoria: "Exportar" },
  { categoria: "Importar" },
  { categoria: "Sincronizar" },
  { categoria: "Banco" },
  { categoria: "Alimentación" },
  { categoria: "Transporte" },
  { categoria: "Salud" },
  { categoria: "Entretenimiento" },
  { categoria: "Educación" },
  { categoria: "Vivienda" },
  { categoria: "Renta" },
  { categoria: "Servicios básicos" },
  { categoria: "Luz" },
  { categoria: "Agua" },
  { categoria: "Internet" },
  { categoria: "Teléfono" },
  { categoria: "Gas" },
  { categoria: "Comida" },
  { categoria: "Medicamentos" },
  { categoria: "Hospital" },
  { categoria: "Clínica" },
  { categoria: "Seguros" },
  { categoria: "Escuela" },
  { categoria: "Universidad" },
  { categoria: "Cursos" },
  { categoria: "Transporte público" },
  { categoria: "Gasolina" },
  { categoria: "Reparaciones" },
  { categoria: "Hogar" },
  { categoria: "Hipoteca" },
  { categoria: "Mantenimiento" },
  { categoria: "Facturas" },
  { categoria: "Ropa" },
  { categoria: "Limpieza" },
  { categoria: "Cuidado personal" },
  { categoria: "Cuidado infantil" },
  { categoria: "Guardería" },
  { categoria: "Mascotas" },
  { categoria: "Veterinario" },
  { categoria: "Vacunas" },
  { categoria: "Préstamos" },
  { categoria: "Intereses" },
  { categoria: "Tarjetas" },
  { categoria: "Efectivo" },
  { categoria: "Impuestos" },
  { categoria: "Deducción" },
  { categoria: "Seguro médico" },
  { categoria: "Seguro de vida" },
  { categoria: "Seguro de auto" },
  { categoria: "Muebles" },
  { categoria: "Electrodomésticos" },
  { categoria: "Gasolina" },
  { categoria: "Remodelación" },
  { categoria: "Deudas" },
  { categoria: "Pagos recurrentes" },
  { categoria: "Suscripciones" },
  { categoria: "Entretenimiento" },
  { categoria: "Cine" },
  { categoria: "Viajes" },
  { categoria: "Vacaciones" },
  { categoria: "Donaciones" },
  { categoria: "Emergencias" },
  
];
